### ISSUE TITLE
Move Stomp connection into Redux for singleton management

### ISSUE THREAD

**Issue by pbucci** [Teleoscope/Teleoscope#157]

**Comment by pbucci** [comment]
We should only be maintaining one connection to RabbitMQ but right now the "TopBar" component is managing the connection. A good design pattern would be to use a singleton by managing the connection through actions/stores. This also opens up our ability to connect to Rabbit across any component without having to reestablish a client connection. 
Here's a nice example:

https://www.pluralsight.com/guides/using-web-sockets-in-your-reactredux-app

**Comment by RedundantComputation** [comment]
Implemented by #187.
