### ISSUE TITLE
Decide on new name for this project

### ISSUE THREAD

**Issue by pbucci** [Teleoscope/Teleoscope#20]
@bestchai suggested a short, snappy name—brainstorm? Working title of CorpusExplorer is OK but could be better branded ;)

**Comment by bestchai** [comment]
CorpraSlicer
Exploracorpus
QAC : **Q**ualitative **A**nalysis of **C**orpra
TAC : **T**ool for **A**nalysis of **C**orpra

**Comment by FlorentinaSimlinger** [comment]
Looks like a good website to help with brainstorming: https://namelix.com/app/?keywords=explore+tool+text

**Comment by pbucci** [comment]
I like TAC since it sounds nice. CAT works too. NLP-Cat --> natural language powered corpora analysis tool?

**Comment by pbucci** [comment]
or maybe CatNIP: Corpora Analysis Tool with Natural Interactive Processing

**Comment by bestchai** [comment]
TAC is at least somewhat google-friendly... though conflicts with a bunch of random orgs. With CAT and CatNIP, folks will have no hope in finding the project. 

Maybe we can all vote among these? Or ask students to bring more names to the next meeting?

**Comment by pbucci** [comment]
Pretty aspirational to imagine SEO for this…

**Comment by bestchai** [comment]
https://www.brainyquote.com/quotes/william_arthur_ward_110017 :-)

**Comment by pbucci** [comment]
lol what i mean to say is I’d rather have a name I enjoy than a name I think is google-able

**Comment by pbucci** [comment]
Results of today's brainstorm:
Catnip
Datnip
Qatnip
TextExp
DiscoverText/DiscoverCorpus
DiscoText
Dean: Data Explorer Analysis NLP
DocUFind
DocExp
DocCorpus
DocuDora
DocX
Browse
DocUBrowse
Natural
Natural Doc Explorer
CorpUBrowse
Cap'n

**Comment by pbucci** [comment]
—> S T A R T R A Q

- startrack 
- nStartrack 
- Shift-8-track
- *-track
- StarTraq
- Invivo ML edition
- universe 
- constellation
- telescope
- lens
- qual_tele
- stellarML
- straq
- straq stomped 
- docCurious
- annotation 
- corpusNaught

**Comment by FlorentinaSimlinger** [comment]
More ideas we came up with today:
- Something with Stardust
- Spacecadettes
- Aethernaut
- teleoscope
- teleonaut
- explorbit
- SpaceGaze
- Something with Helios
- some world play around uni-verse

**Comment by pbucci** [comment]
Teleoscope
