### ISSUE TITLE
When there are no groups, folder drop down should not show an empty list

### ISSUE THREAD

**Issue by bestchai** [Teleoscope/Teleoscope#386]
Currently, if there are no groups, the folder icon click next to a doc shows an empty list of groups, which looks like this:

<img width="374" alt="image" src="https://user-images.githubusercontent.com/353346/231018194-65abc635-5b14-4ccb-86c4-f99005624d30.png">

The fix is to probably to not show anything when no groups exist and the icon is clicked.

**Comment by marasolen** [comment]
I don't agree that nothing should show up when there are no options. I think there needs to be at least some feedback that the interaction was registered. I think that the box should say something that tells the user that no groups exist.
