### ISSUE TITLE
Update interface standard on Wiki

### ISSUE THREAD

**Issue by pbucci** [Teleoscope/Teleoscope#58]
Update the interface standard on the wiki to reflect the changes requested below.

re: #54 #55 #56 #57

https://github.com/Teleoscope/Teleoscope/wiki/Interface-standard

**Comment by RedundantComputation** [comment]
Updated with the `positive_docids` field, do we also want to specify on this page how the teleoscope collection is modified and spell out all the components of the collection?

**Comment by pbucci** [comment]
yes, although I guess this isn't a message format as much as a return object for the API so maybe a 2nd table for that?

**Comment by RedundantComputation** [comment]
To-do: Copy an RFC style format?

Top-level: Specify action prerequisites and what request corresponds to the action prerequisites and then users can scroll down to the appropriate request type.

For each request: Specify the JSON object and what the frontend is passing to the backend.
