### ISSUE TITLE
Installation bugs

### ISSUE THREAD

**Issue by PrayusShrestha** [Teleoscope/Teleoscope#9]
I ran into issues where not all the modules needed for installation were explicitly mentioned in the README as something to install.

Proposed Solution: store all packages needed to be installed in a requirements.txt file. That way we can just ```pip install -r requirement.txt``` to install all the needed modules.

**Comment by AJS1NGH** [comment]
- instructions for tunnelling & port forwarding might be needed

**Comment by pbucci** [comment]
^^ both sound good to me!

**Comment by FlorentinaSimlinger** [comment]
- README in general should be made clearer: for instance, we could specify which access rights need to be requested at the very top so that users don't start with the installation process until they have everything they need.

**Comment by pbucci** [comment]
This all looks good! Can people please submit their suggested changes the same as a bug fix? I.e., make the change and send a pull request.

**Comment by FlorentinaSimlinger** [comment]
note for me: install script is missing install of npm
