### ISSUE TITLE
Implement Teleoscope history based on current session prototype

### ISSUE THREAD

**Issue by pbucci** [Teleoscope/Teleoscope#99]

**Comment by pbucci** [comment]
I’m not sure where you’re at with this one, but I implemented a very simple version of saving sessions state in the current branch (see the “sessions” collection on mongodb). For no good reason, almost all of the logic is implemented in TopBar.js. 

Rather than prototyping it myself, I’ve left this as a TODO for you so that you can take a shot at a database design here. I prefer the style of not having many hierarchical documents, but instead using UID or OID references to point to different documents. This supports flexibility.

So an example could be that each teleoscope has a “history” item as part of its hierarchy, e.g.:
```
teleoscope_1: {
      …
      history: {
          …
      }
}
```
Or there could be a history collection:
```
history: {
     actions: {
         action1: {
            timestamp
            actionName
         }
     }
}
```

And then the teleoscope object’s history just contains references to a selection of the overall system history.

I’d say just choose the easiest one. I’d have to spend some time designing to figure that out, but it’s probably better for you to do it :) or to lead a discussion with me/Ivan/team about it.

**Comment by RedundantComputation** [comment]
Use forward and back maybe by incrementing and decrementing a counter?

**Comment by RedundantComputation** [comment]
Maybe go more specific, take a snapshot of the individual elements of the UI.

**Comment by RedundantComputation** [comment]
Make the user responsible for supplying an arg that tells us where to index in the history. Save will always add to the end. At some point we can think about adding features like allowing the user to delete from point X in the history, but right now just save everything.
